const libraries={
 email:["Reorganize your inbox labels by emotional tone","Draft a signature for a future job title","Research whether 'Best' sounds passive-aggressive","Archive every newsletter from 2021","Design a tiny flag for unread messages"],
 study:["Choose the perfect study font","Rank every highlighter by seriousness","Make a playlist called Academic Weather","Calculate how long studying would take if started yesterday","Rewrite the title page with better margins"],
 clean:["Photograph the mess for archival purposes","Sort one drawer by object personality","Research the history of dust","Create a donation box label system","Clean the cleaning supplies first"],
 write:["Rename the document three times","Research a fact that will not appear in the draft","Choose a more authoritative cursor color","Format the bibliography before writing","Draft an acknowledgements section"],
 work:["Create a meeting about avoiding meetings","Color-code the task by hypothetical urgency","Build a dashboard for one checkbox","Research an easier version of the task","Write a status update about beginning soon"],
 default:["Alphabetize three nearby objects","Design a flag for the task","Find the quietest rectangle in the room","Make an unnecessarily specific playlist","Research the origin of the word 'later'","Organize something that was already organized","Take a strategic hydration intermission","Rename every folder involved"]
};
const stamps=["MINOR TASK\nMAJOR CEREMONY","BUSY BEYOND\nRECOGNITION","DETOUR\nSPECIALIST","ZERO PROGRESS\nEXCELLENT FORM","LATER\nACHIEVED"];
const state={task:"",quests:[],done:new Set(),started:0,tick:null,focus:null,actual:0};
const $=q=>document.querySelector(q),form=$("#task-form"),input=$("#task"),plan=$("#plan"),empty=$("#empty");
function clock(){const d=new Date();$("#clock").textContent=d.toLocaleTimeString([], {hour12:false})}clock();setInterval(clock,1000);
document.addEventListener("pointermove",e=>{$("#glow").style.left=e.clientX+"px";$("#glow").style.top=e.clientY+"px"});
input.addEventListener("input",()=>$("#char-count").textContent=input.value.length);
document.querySelectorAll(".examples button").forEach(b=>b.onclick=()=>{input.value=b.textContent;input.dispatchEvent(new Event("input"));input.focus()});
function category(text){text=text.toLowerCase();if(/email|inbox|reply/.test(text))return"email";if(/study|exam|test|homework|class/.test(text))return"study";if(/clean|room|laundry|closet/.test(text))return"clean";if(/write|report|essay|draft|article/.test(text))return"write";if(/work|project|meeting|presentation/.test(text))return"work";return"default"}
function shuffle(a,seed){let x=[...a],n=[...seed].reduce((s,c)=>s+c.charCodeAt(0),0);for(let i=x.length-1;i>0;i--){n=(n*9301+49297)%233280;let j=Math.floor(n/233280*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function generate(task){const pool=[...libraries[category(task)],...libraries.default];state.task=task;state.quests=shuffle(pool,task+Date.now()).slice(0,5);state.done.clear();state.started=Date.now();empty.hidden=true;plan.hidden=false;$("#plan-title").textContent=`Avoiding: ${task}`;render();clearInterval(state.tick);state.tick=setInterval(metrics,1000);metrics()}
function render(){const map=$("#quest-map");map.querySelectorAll(".quest").forEach(x=>x.remove());state.quests.forEach((q,i)=>{const b=document.createElement("button");b.className=`quest ${state.done.has(i)?"done":""} ${i>0&&!state.done.has(i-1)?"locked":""}`;b.innerHTML=`<small>DETOUR ${String(i+1).padStart(2,"0")}</small><b>${q}</b><span>${state.done.has(i)?"PERFORMED ✓":"MARK COMPLETE"}</span><i></i>`;b.onclick=()=>complete(i);map.append(b)});requestAnimationFrame(drawRoute)}
function drawRoute(){const map=$("#quest-map"),r=map.getBoundingClientRect(),nodes=[...map.querySelectorAll(".quest")].map(n=>{const b=n.getBoundingClientRect();return{x:b.left-r.left+b.width/2,y:b.top-r.top+b.height/2}});if(!nodes.length)return;$("#route").setAttribute("d",nodes.map((p,i)=>`${i?"L":"M"}${p.x},${p.y}`).join(" "))}
function complete(i){if(state.done.has(i))return;state.done.add(i);render();const stamp=$("#stamp");stamp.textContent=stamps[Math.min(state.done.size-1,stamps.length-1)];stamp.classList.remove("pop");void stamp.offsetWidth;stamp.classList.add("pop");metrics();if(state.done.size===5)setTimeout(()=>generate(state.task),850)}
function metrics(){if(!state.started)return;const seconds=Math.floor((Date.now()-state.started)/1000),m=String(Math.floor(seconds/60)).padStart(2,"0"),s=String(seconds%60).padStart(2,"0");$("#time-lost").textContent=`${m}:${s}`;$("#completed").textContent=state.done.size;$("#theater").textContent=Math.min(99,state.done.size*18+Math.floor(seconds/20))+"%";$("#actual").textContent=state.actual;$("#delay-index").textContent=String(Math.min(99,17+state.done.size*14+Math.floor(seconds/12))).padStart(2,"0");$("#time-saved").textContent=`—${12+state.done.size*7} MIN`}
form.addEventListener("submit",e=>{e.preventDefault();if(input.value.trim())generate(input.value.trim())});$("#new-plan").onclick=()=>state.task&&generate(state.task);window.addEventListener("resize",drawRoute);
const dialog=$("#focus-dialog");$("#focus").onclick=()=>{$("#focus-task").textContent=state.task||"The task you have not told the machine about.";dialog.showModal()};$(".close").onclick=()=>dialog.close();
$("#start-focus").onclick=()=>{clearInterval(state.focus);let seconds=300;const out=$("#focus-timer");state.focus=setInterval(()=>{seconds--;out.textContent=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;if(seconds<=0){clearInterval(state.focus);out.textContent="DONE"}},1000)};
$("#declare-done").onclick=()=>{state.actual++;$("#actual").textContent=state.actual;dialog.close();state.task="";state.started=0;plan.hidden=true;empty.hidden=false;input.value="";$("#char-count").textContent="0";clearInterval(state.tick)};
