const pools={email:["Re-label your inbox by emotional tone","Invent a future email signature","Research whether 'Best' is hostile","Design an unread-message flag"],study:["Rank highlighters by seriousness","Make an Academic Weather playlist","Choose the perfect study font","Calculate yesterday's ideal schedule"],clean:["Photograph the mess for history","Sort objects by personality","Research the history of dust","Name the cleaning supplies"],write:["Rename the document three times","Find a fact you will not use","Choose an authoritative cursor","Design the report's flag"],default:["Pop twelve strategic bubbles","Alphabetize nearby objects","Find the quietest rectangle","Rename three imaginary folders","Design a flag for the task","Memorize an unnecessary pattern","Hold a button for no good reason","Mix the official color of later"]};
const art=["clock","lamp","snail","paper plane","key","pen","paper stack","thread","chair","clip","envelope","file cabinet"],S={task:"",q:[],done:new Set(),start:0,active:0,tick:null,focus:null};const $=x=>document.querySelector(x);
setInterval(()=>$("#clock").textContent=new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}),1000);document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>$("#task").value=b.textContent);
function cat(t){t=t.toLowerCase();if(/email|inbox/.test(t))return"email";if(/study|exam|test/.test(t))return"study";if(/clean|room/.test(t))return"clean";if(/write|report|essay/.test(t))return"write";return"default"}function mix(a){return[...a].sort(()=>Math.random()-.5)}
function begin(t){S.task=t;S.done.clear();S.start=Date.now();S.q=mix([...(pools[cat(t)]||[]),...pools.default]).slice(0,5);$("#welcome").hidden=true;$("#play").hidden=false;$("#realTask").textContent=t;render();clearInterval(S.tick);S.tick=setInterval(metrics,1000);metrics()}document.querySelector("form").onsubmit=e=>{e.preventDefault();let t=$("#task").value.trim();if(t)begin(t)};
function render(){let q=$("#quests");q.innerHTML="";S.q.forEach((t,i)=>{let b=document.createElement("button"),lock=i&&!S.done.has(i-1),sprite=(i+S.q.join('').length)%art.length;b.className=`quest ${S.done.has(i)?"done":""} ${lock?"locked":""}`;b.innerHTML=`<small>DETOUR 0${i+1}</small><strong>${t}</strong><b class="s${sprite}" aria-label="${art[sprite]}">${S.done.has(i)?"✓":art[sprite]}</b><span>${S.done.has(i)?"ACTUALLY PERFORMED":"OPEN THE LITTLE DOOR"}</span>`;b.onclick=()=>!lock&&!S.done.has(i)&&openGame(i);q.append(b)})}
function type(t,i){t=t.toLowerCase();if(/flag|color|cursor/.test(t))return"color";if(/rename|label|signature|font/.test(t))return"rename";if(/find|research|history|fact|schedule/.test(t))return"hunt";if(/sort|rank|alphabet/.test(t))return"sort";if(/memorize|pattern|playlist/.test(t))return"memory";if(/hold|photograph/.test(t))return"hold";return"bubbles"}
function openGame(i){S.active=i;$("#gameTitle").textContent=S.q[i];let typ=type(S.q[i],i),a=$("#activity"),n=0;a.className=typ;a.innerHTML="";
 if(typ==="bubbles"){$("#instruction").textContent="Rescue each tiny desk object from its glassy daydream.";a.className="bubbles";for(let j=0;j<12;j++){let b=document.createElement("button");b.className=`sprite s${j}`;b.setAttribute("aria-label",art[j]);b.onclick=()=>{if(!b.classList.contains("done")){b.classList.add("done");prog(++n,12)}};a.append(b)}prog(0,12)}
 else if(typ==="sort"){$("#instruction").textContent="Send each wandering object through the imaginary filing chute.";a.className="things";art.slice(0,6).forEach((x,j)=>{let b=document.createElement("button");b.className=`sprite s${j}`;b.setAttribute("aria-label",x);b.onclick=()=>{if(!b.classList.contains("done")){b.classList.add("done");prog(++n,6)}};a.append(b)});prog(0,6)}
 else if(typ==="rename"){$("#instruction").textContent="Give the tiny filing cabinet three names it can grow into.";a.className="rename";a.innerHTML='<div class="folder-art">filing cabinet</div><input placeholder="A very important name"><button>FILE THIS NAME</button><p></p>';let inp=a.querySelector("input");a.querySelector("button").onclick=()=>{if(inp.value.trim()){a.querySelector("p").textContent+=`${++n}. ${inp.value}_FINAL `;inp.value="";prog(n,3)}};prog(0,3)}
 else if(typ==="hunt"){$("#instruction").textContent="Find the sleepy snail while the office objects politely evade you.";a.className="hunt";for(let j=0;j<9;j++){let b=document.createElement("button"),s=j===7?2:j%12;b.className=`sprite s${s}`;b.setAttribute("aria-label",j===7?"sleepy snail":art[s]);b.style.left=(j*10%78)+"%";b.style.top=(j*27%62)+"%";b.onclick=()=>j===7?prog(1,1):(b.style.left=Math.random()*76+"%",b.style.top=Math.random()*58+"%");a.append(b)}prog(0,1)}
 else if(typ==="color"){$("#instruction").textContent="Create and approve the official color of this delay.";a.className="color-game";a.innerHTML='<div class="swatch">DELAY</div><input type="color" value="#ff68b4"><select><option>sparkly</option><option>serious</option><option>suspicious</option></select><button>APPROVE COLOR</button>';a.querySelector('input').oninput=e=>a.querySelector('.swatch').style.background=e.target.value;a.querySelector('button').onclick=()=>prog(1,1);prog(0,1)}
 else if(typ==="memory"){$("#instruction").textContent="Repeat the tiny desk parade: clock, snail, lamp, paper plane.";a.className="memory";let seq=[0,2,1,3],pos=0;a.innerHTML='<button aria-label="clock">clock</button><button aria-label="lamp">lamp</button><button aria-label="snail">snail</button><button aria-label="paper plane">paper plane</button><p>clock → snail → lamp → paper plane</p>';a.querySelectorAll('button').forEach((b,j)=>b.onclick=()=>{if(j===seq[pos]){pos++;prog(pos,4)}else{pos=0;prog(0,4)}});prog(0,4)}
 else{$("#instruction").textContent="Press and hold until the ceremonial meter fills.";a.className="hold";a.innerHTML='<button>HOLD ME<br>DO NOT BE USEFUL</button>';let timer;a.querySelector('button').onpointerdown=()=>timer=setInterval(()=>{n++;prog(n,20)},100);a.querySelector('button').onpointerup=a.querySelector('button').onpointerleave=()=>clearInterval(timer);prog(0,20)}$("#game").showModal()}
function prog(n,t){$("#progress").textContent=`${n} / ${t}`;$("#bar").style.width=Math.min(100,n/t*100)+"%";if(n>=t)setTimeout(complete,300)}function complete(){S.done.add(S.active);$("#game").close();render();metrics();$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),1700)}function metrics(){let s=Math.floor((Date.now()-S.start)/1000);$("#lost").textContent=`${String(s/60|0).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;$("#count").textContent=S.done.size;$("#fake").textContent=Math.min(99,S.done.size*18+(s/15|0))+"%"}
$(".x").onclick=()=>$("#game").close();$("#shuffle").onclick=()=>begin(S.task);$("#restart").onclick=()=>{clearInterval(S.tick);$("#play").hidden=true;$("#welcome").hidden=false};$("#actually").onclick=()=>{$("#focusTask").textContent=S.task;$("#focus").showModal()};$(".fx").onclick=()=>$("#focus").close();$("#five").onclick=()=>{clearInterval(S.focus);let s=300;S.focus=setInterval(()=>{s--;$("#timer").textContent=`${String(s/60|0).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;if(!s)clearInterval(S.focus)},1000)};$("#finished").onclick=()=>{$("#focus").close();$("#restart").click();$("#toast").textContent="WAIT… YOU ACTUALLY DID IT?!";$("#toast").classList.add("show")};
